### ISSUE TITLE
Load .env.username

### ISSUE THREAD

**Issue by nicholasf** [jpfuentes2/go-env#5]
We need a way to load user specific variables; for e.g. to set the location of a key store on a machine, which may vary according to developer.

I imagine we could look for the .env file with the user's system name.

```
.env.nicholasf
.env.test.nicholasf
//etc
```

**Comment by jpfuentes2** [comment]
What if we used `GOENV=/absolute/path/to/specific-env-file.env` rather than `GOENV=test` and presuming it's `test.env`?

**Comment by nicholasf** [comment]
Hrm, or we could just list .envs in .gitignore, and supply a .env.example for each dev to run with (kind of analogous to what peeps do with database.yml)?

**Comment by jpfuentes2** [comment]
https://github.com/bkeepers/dotenv#multiple-rails-environments

`.env.local`?

**Comment by jpfuentes2** [comment]
closed by #6
